<?php

class ContactsDao extends BaseDao
{
    protected $db = 'main.db';
    protected $table = 'Contacts';
    protected $field_name = array(
        'id',
        'is_permanent',
        'type',
        'skypename',
        'pstnnumber',
        'aliases',
        'fullname',
        'birthday',
        'gender',
        'languages',
        'country',
        'province',
        'city',
        'phone_home',
        'phone_office',
        'phone_mobile',
        'emails',
        'homepage',
        'about',
        'avatar_image',
        'mood_text',
        'rich_mood_text',
        'timezone',
        'capabilities',
        'profile_timestamp',
        'nrof_authed_buddies',
        'ipcountry',
        'avatar_timestamp',
        'mood_timestamp',
        'received_authrequest',
        'authreq_timestamp',
        'lastonline_timestamp',
        'availability',
        'displayname',
        'refreshing',
        'given_authlevel',
        'given_displayname',
        'assigned_speeddial',
        'assigned_comment',
        'alertstring',
        'lastused_timestamp',
        'authrequest_count',
        'assigned_phone1',
        'assigned_phone1_label',
        'assigned_phone2',
        'assigned_phone2_label',
        'assigned_phone3',
        'assigned_phone3_label',
        'buddystatus',
        'isauthorized',
        'popularity_ord',
        'isblocked',
        'authorization_certificate',
        'certificate_send_count',
        'account_modification_serial_nr',
        'saved_directory_blob',
        'nr_of_buddies',
        'server_synced',
        'contactlist_track',
        'last_used_networktime',
        'authorized_time',
        'sent_authrequest',
        'sent_authrequest_time',
        'sent_authrequest_serial',
        'buddyblob',
        'cbl_future',
        'node_capabilities',
        'revoked_auth',
        'added_in_shared_group',
        'in_shared_group',
        'authreq_history',
        'profile_attachments',
        'stack_version',
        'offline_authreq_id',
        'node_capabilities_and',
        'authreq_crc',
        'authreq_src',
        'pop_score',
        'authreq_nodeinfo',
        'main_phone',
        'unified_servants',
        'phone_home_normalized',
        'phone_office_normalized',
        'phone_mobile_normalized',
        'sent_authrequest_initmethod',
        'authreq_initmethod',
        'verified_email',
        'verified_company',
        'sent_authrequest_extrasbitmask',
        'extprop_contact_ab_uuid',
        'extprop_external_data',
        'extprop_last_sms_number',
        'extprop_viral_upgrade_campaign_id',
        'hashed_emails',
        'external_id',
        'external_system_id',
        'liveid_cid',
    );

    protected $queries = array(
        "select" => array(
            "sql" => "select * from __TABLE_NAME__",
        ),
    );
}

/* table schema

CREATE TABLE "Contacts"
(
    id INTEGER NOT NULL PRIMARY KEY,
    is_permanent INTEGER,
    type INTEGER,
    skypename TEXT,
    pstnnumber TEXT,
    aliases TEXT,
    fullname TEXT,
    birthday INTEGER,
    gender INTEGER,
    languages TEXT,
    country TEXT,
    province TEXT,
    city TEXT,
    phone_home TEXT,
    phone_office TEXT,
    phone_mobile TEXT,
    emails TEXT,
    homepage TEXT,
    about TEXT,
    avatar_image BLOB,
    mood_text TEXT,
    rich_mood_text TEXT,
    timezone INTEGER,
    capabilities BLOB,
    profile_timestamp INTEGER,
    nrof_authed_buddies INTEGER,
    ipcountry TEXT,
    avatar_timestamp INTEGER,
    mood_timestamp INTEGER,
    received_authrequest TEXT,
    authreq_timestamp INTEGER,
    lastonline_timestamp INTEGER,
    availability INTEGER,
    displayname TEXT,
    refreshing INTEGER,
    given_authlevel INTEGER,
    given_displayname TEXT,
    assigned_speeddial TEXT,
    assigned_comment TEXT,
    alertstring TEXT,
    lastused_timestamp INTEGER,
    authrequest_count INTEGER,
    assigned_phone1 TEXT,
    assigned_phone1_label TEXT,
    assigned_phone2 TEXT,
    assigned_phone2_label TEXT,
    assigned_phone3 TEXT,
    assigned_phone3_label TEXT,
    buddystatus INTEGER,
    isauthorized INTEGER,
    popularity_ord INTEGER,
    isblocked INTEGER,
    authorization_certificate BLOB,
    certificate_send_count INTEGER,
    account_modification_serial_nr INTEGER,
    saved_directory_blob BLOB,
    nr_of_buddies INTEGER,
    server_synced INTEGER,
    contactlist_track INTEGER,
    last_used_networktime INTEGER,
    authorized_time INTEGER,
    sent_authrequest TEXT,
    sent_authrequest_time INTEGER,
    sent_authrequest_serial INTEGER,
    buddyblob BLOB,
    cbl_future BLOB,
    node_capabilities INTEGER,
    revoked_auth INTEGER,
    added_in_shared_group INTEGER,
    in_shared_group INTEGER,
    authreq_history BLOB,
    profile_attachments BLOB,
    stack_version INTEGER,
    offline_authreq_id INTEGER,
    node_capabilities_and INTEGER,
    authreq_crc INTEGER,
    authreq_src INTEGER,
    pop_score INTEGER,
    authreq_nodeinfo BLOB,
    main_phone TEXT,
    unified_servants TEXT,
    phone_home_normalized TEXT,
    phone_office_normalized TEXT,
    phone_mobile_normalized TEXT,
    sent_authrequest_initmethod INTEGER,
    authreq_initmethod INTEGER,
    verified_email BLOB,
    verified_company BLOB,
    sent_authrequest_extrasbitmask INTEGER,
    extprop_contact_ab_uuid TEXT,
    extprop_external_data TEXT,
    extprop_last_sms_number TEXT,
    extprop_viral_upgrade_campaign_id INTEGER,
    hashed_emails TEXT,
    external_id TEXT,
    external_system_id TEXT,
    liveid_cid TEXT
);
CREATE INDEX IX_Contacts_buddystatus ON Contacts (buddystatus);
CREATE INDEX IX_Contacts_skypename ON Contacts (skypename);
*/
